title:
  en: Maze Generator and Solver
  es: Generador y Solucionador de Laberintos
finished: finished
descriptionShort:
  en: Mazes are an interesting application of graph and algorithm theory. They can be represented in many ways, but the objective is always to navigate from one tile to another (the exit). Here, we use pathfinding algorithms like A* or Greedy to find the best solution. Click to see how mazes are generated and solved step by step!
  es: "Los laberintos son una aplicación muy interesante de la teoría de grafos y algoritmos. Se pueden representar de muchas maneras, pero el objetivo siempre es el mismo: encontrar el camino desde el punto de inicio hasta la salida. Aquí utilizo algoritmos como A* o Greedy para resolverlos paso a paso. ¡Haz clic y descubre cómo funcionan!"
descriptionLong:
  en: |
    Mazes are an interesting application of graph and algorithm theory. They can be represented in many ways, but the objective is always to navigate from one tile to another (the exit). Using Python, Pygame, and NumPy, we employ pathfinding algorithms like A* or Greedy to find the best solution. Two different maze generation algorithms are used: Origin Shift and DFS. Various strategies are then applied to solve them based on different heuristics. Many others can be implemented (also, since DFS is a somewhat simplistic maze generator), so you are more than welcome to contribute!
  es: |
    En este proyecto exploro la teoría de grafos aplicada a los laberintos, donde el objetivo es siempre encontrar la ruta más eficiente desde la entrada hasta la salida. Usando Python, Pygame y NumPy, he implementado algoritmos como A* y Greedy para resolverlos. También he utilizado dos métodos para generarlos: Origin Shift y DFS. Este último es algo aburrido, por lo que estaría bien implementar otros y compararlo. Modificar le código es sencillo, si tienes ideas o quieres contribuir con nuevas mejoras, ¡eres más que bienvenido!
technologies: [python, pygame, numpy]
tags: [other]
logo: readme_images/MazeSolver (1).webp
screenShoots:
  - readme_images/MazeSolver (1).webp
  - readme_images/MazeSolver (2).webp
  - readme_images/MazeSolver (3).webp
  - readme_images/MazeSolver (4).webp
  - readme_images/MazeSolver (5).webp
  - readme_images/MazeSolver (6).webp
  - readme_images/MazeSolver (7).webp
  - readme_images/MazeSolver (8).webp
youtube: bZt4bsz9n9Q
slug: Maze-Generator-Solver
order: 55
featured: false
